[project]
name = "vehicle-fuel-efficiency-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anuj04432", email = "anujwagmore835@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
vehicle-fuel-efficiency-prediction = "vehicle_fuel_efficiency_prediction:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
